### ISSUE TITLE
Add SignedExtension to check Metadata Root Hash

### ISSUE THREAD

**Issue by SBalaguer** [paritytech/polkadot-sdk#2016] opened 2023-10-24 20:15 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Offline signer experience in the Polkadot ecosystem can be massively improved. Today there is either too much manual, no scalable work (Ledger) or simply too much trust deposit on a third party (Polkadot Vault / Kampela). 
The Zondax and Alzymologist team provided a way to solve these issues to the Polkadot Community on [Ref #62](https://polkadot.polkassembly.io/referenda/62). This gave way to the 'Metadata for Offline Signers' project that can be tracked [here](https://github.com/Alzymologist/metadata-offline-project/).

Related: https://github.com/paritytech/polkadot-sdk/issues/291

### Request

The proposed solution is to maximize the usage of the Metadata so as to provide the right information to the offline signer. As this needs to be passed to the signer by some third party software, in order to avoid attacks the proposal is to add a new SignedExtension that would add the check of the Metadata Root Hash. This will make it so that any transaction sent from an offline device will include the root hash and this information will be then checked by the runtime.

As to how calculate this metadata root hash, there's a <del>[spec](https://github.com/Alzymologist/metadata-offline-project/blob/main/milestone_1.md)</del> [description](https://github.com/Alzymologist/metadata-offline-project/blob/main/milestone_1.md) and a [reference implementation](https://github.com/Alzymologist/metadata-shortener)

### Are you willing to help with this request?

Yes!

**Comment by ggwpez** [comment] 2023-10-24 20:18
Yea sounds good. Maybe could to for an RFC (but not sure if its a must here) https://github.com/polkadot-fellows/RFCs

**Comment by SBalaguer** [comment] 2023-10-24 20:30
Yep, not super sure myself either! If need be down the line, happy to do it :)

**Comment by bkchr** [comment] 2023-10-24 21:41
> there's a [spec](https://github.com/Alzymologist/metadata-offline-project/blob/main/milestone_1.md)

That is not really a spec ;)

**Comment by bkchr** [comment] 2023-10-24 22:00
Having a RFC for the spec would be a good start IMO.

**Comment by SBalaguer** [comment] 2023-10-24 22:25
@bkchr edit from spec to description to make it clearer. We'll move ahead then with the RFC first and then come back here.

**Comment by bkchr** [comment] 2023-10-25 12:00
Ty! The extension will actually not be that complicated, more integrating this into the build process. However, even the integration to the build process will be easy against the metadata merkleization.

**Comment by bkchr** [comment] 2024-04-24 21:30
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/291

**Closed by bkchr** 2024-04-24 21:30 UTC
Labels: I5-enhancement
