### ISSUE TITLE
Publish log-enabled runtime versions

### ISSUE THREAD

**Issue by franciscoaguirre** [paritytech/polkadot-sdk#6123] opened 2024-10-18 13:22 UTC
One of the most annoying things about debugging XCMs is that the live runtimes don't have the logs enabled.
We could enable logs on the live runtimes but no one has them turned on anyway since they're so noisy, and they take up space and performance.
The only scenarios where we want logs are when running local nodes or replaying some transaction locally, for example with chopsticks.
A good solution for this is then to just publish a "debug" version of each runtime that can be used with chopsticks.
Since we have so many runtimes already in our releases, we could just upload a zip file with all of them.
They could also be useful for offline development.

**Comment by bkchr** [comment] 2024-10-19 08:53
Duplicate of: https://github.com/polkadot-fellows/runtimes/issues/268

**Closed by bkchr** 2024-10-19 08:53 UTC
