### ISSUE TITLE
Block blocked at height 19720317

### ISSUE THREAD

**Issue by lansehuiyi6** [paritytech/polkadot-sdk#3557] opened 2024-03-04 06:21 UTC
version 0.9.42

<html>
<body>

2024-03-04 05:43:19 💤 Idle (5 peers), best: #19720317 (0xe126…1167), finalized #19720320 (0x9f0e…9e93), ⬇ 2.5kiB/s ⬆ 54.3kiB/s
--
  | 2024-03-04 05:43:23 💔 Error importing block 0xaf540fcfaf1ace474c8a8fe96ca1d2501de72990d3f04e8639219e97f4b99436: consensus error: Chain lookup failed: No block weight for parent header.
  | 2024-03-04 05:43:24 💤 Idle (5 peers), best: #19720317 (0xe126…1167), finalized #19720320 (0x9f0e…9e93), ⬇ 634.7kiB/s ⬆ 182.9kiB/s
  | 2024-03-04 05:43:25 💔 Error importing block 0xaf540fcfaf1ace474c8a8fe96ca1d2501de72990d3f04e8639219e97f4b99436: consensus error: Chain lookup failed: No block weight for parent header.
  | 2024-03-04 05:43:29 💤 Idle (4 peers), best: #19720317 (0xe126…1167), finalized #19720320 (0x9f0e…9e93), ⬇ 328.1kiB/s ⬆ 53.6kiB/s
  | 2024-03-04 05:43:34 💔 Error importing block 0xaf540fcfaf1ace474c8a8fe96ca1d2501de72990d3f04e8639219e97f4b99436: consensus error: Chain lookup failed: No block weight for parent header.
  | 2024-03-04 05:43:34 💤 Idle (4 peers), best: #19720317 (0xe126…1167), finalized #19720320 (0x9f0e…9e93), ⬇ 480.5kiB/s ⬆ 26.9kiB/s
  | 2024-03-04 05:43:38 💔 Error importing block 0xaf540fcfaf1ace474c8a8fe96ca1d2501de72990d3f04e8639219e97f4b99436: consensus error: Chain lookup failed: No block weight for parent header.

</body>
</html>

**Comment by skunert** [comment] 2024-03-04 09:00
Thanks for the report! This is essentially a duplicate of https://github.com/paritytech/polkadot-sdk/issues/3550, so we should close this. See the discussion there for workarounds.

**Closed by skunert** 2024-03-04 09:00 UTC
Labels: I10-unconfirmed
