### ISSUE TITLE
Migration issues with async backing turned on

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/polkadot-sdk#3932] opened 2024-04-02 02:27 UTC
Because async backing will make the parachain's out-of-block time become 6s, which will break the time-related code. For example pallet-vesting. or other custom pallets.
I wonder if there will be a unified migration solution? Or is it only possible to manually store migrations one by one.

**Comment by bkchr** [comment] 2024-04-02 07:24
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/3268

**Closed by bkchr** 2024-04-02 07:24 UTC
Labels: I10-unconfirmed
