### ISSUE TITLE
^C upon node start leads to a live lock

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot-sdk#1779] opened 2023-10-03 12:56 UTC
If you start a polkadot node f60318f and more or less right away start ^C it, it will not shutdown but instead will lock up and print the following messages until killed:

```
2023-10-03 13:54:01 netlink socket stream shut down
2023-10-03 13:54:01 error flushing netlink socket: Custom { kind: Other, error: "A Tokio 1.x context was found, but it is being shutdown." }
2023-10-03 13:54:01 if watch returned an error: rtnetlink socket closed
2023-10-03 13:54:01 failed to read from netlink socket: Custom { kind: Other, error: "A Tokio 1.x context was found, but it is being shutdown." }
2023-10-03 13:54:01 netlink socket stream shut down
```

**Comment by bkchr** [comment] 2023-10-03 13:32
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/671

**Closed by bkchr** 2023-10-03 13:32 UTC
Labels: I2-bug, I10-unconfirmed
