### ISSUE TITLE
Cumulus: gossip block announcement before import

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#5255] opened 2024-08-06 11:25 UTC
Currently my understanding is that we don't gossip the block announcement until we have imported it successfully. 

For elastic scaling parachains this works fine as long as the next block author is directly connected to the current one. If they are not directly connected, the announcement will arrive much later to the next author: `number_of_hops x import_duration`. This leads to the next author creating a fork and stalling the progress of the parachain.

CC @skunert

**Comment by skunert** [comment] 2024-08-06 11:38
Yes, there is this issue https://github.com/paritytech/polkadot-sdk/issues/65 together with a previous solving attempt https://github.com/paritytech/substrate/pull/8052 . However have not looked into the details what the exact problems with previous attempt were.

**Comment by burdges** [comment] 2024-08-08 09:35
Is this required even if the same collator builds the whole batch of elastic scalled blocks?  Aka it's so the other parachain nodes can keep up?

**Comment by sandreim** [comment] 2024-08-08 12:22
It is only required when the author of the next block is different from current one. With AURA it will always be needed, unless there is just a single collator, or we make changes so each author gets more than one slot to author.

**Comment by sandreim** [comment] 2024-08-08 12:23
Other nodes should keep up just fine, they don’t need to do anything special.

**Comment by bkchr** [comment] 2024-08-12 20:00
Duplicate of #65.

**Closed by bkchr** 2024-08-12 20:00 UTC
Labels: I9-optimisation, T9-cumulus
