### ISSUE TITLE
libp2p netlink error

### ISSUE THREAD

**Issue by tdimitrov** [paritytech/polkadot-sdk#4717] opened 2024-06-05 20:45 UTC
While being on-call I got paged for this error on a kusama validator `kusama-validator-bhs5-0`:
```
2024-06-05 22:05:18	2024-06-05 19:05:17.991 ERROR tokio-runtime-worker libp2p_mdns::behaviour: if watch returned an error: rtnetlink socket closed
2024-06-05 22:05:18	2024-06-05 19:05:17.991 ERROR tokio-runtime-worker netlink_proto::framed: failed to read from netlink socket: Custom { kind: Other, error: "A Tokio 1.x context was found, but it is being shutdown." }
```

It was a spike lasting just a few minutes. From 19:04 to 19:07 UTC on Jun 5th.

**Comment by alexggh** [comment] 2024-06-06 06:30
It happens at node restart it is a duplicate of https://github.com/paritytech/polkadot-sdk/issues/671.

**Comment by alexggh** [comment] 2024-06-06 06:31
It happens at node restart https://github.com/paritytech/polkadot-sdk/issues/671

**Closed by alexggh** 2024-06-06 06:31 UTC
