### ISSUE TITLE
Crash with Polkadot 1.14.0 version

### ISSUE THREAD

**Issue by 3eph1r0th** [paritytech/polkadot-sdk#5089] opened 2024-07-21 06:45 UTC
2024-07-21 01:26:30 💤 Idle (21 peers), best: #21736411 (0x9ee1…3e3c), finalized #21736409 (0x32e1…d0bd), ⬇ 607.7kiB/s ⬆ 177.0kiB/s
2024-07-21 01:26:30 🏆 Imported #21736412 (0x9ee1…3e3c → 0x76e8…82bc)
2024-07-21 01:26:35 💤 Idle (19 peers), best: #21736412 (0x76e8…82bc), finalized #21736409 (0x32e1…d0bd), ⬇ 547.0kiB/s ⬆ 759.4kiB/s
2024-07-21 01:26:38 🏆 Imported #21736413 (0x76e8…82bc → 0xe3d3…6193)
2024-07-21 01:26:40 💤 Idle (19 peers), best: #21736413 (0xe3d3…6193), finalized #21736410 (0x1a20…929d), ⬇ 674.1kiB/s ⬆ 359.0kiB/s
2024-07-21 01:26:42 🏆 Imported #21736414 (0xe3d3…6193 → 0x6b46…9976)
2024-07-21 01:26:45 💤 Idle (19 peers), best: #21736414 (0x6b46…9976), finalized #21736411 (0x9ee1…3e3c), ⬇ 854.0kiB/s ⬆ 762.0kiB/s
2024-07-21 01:26:48 🏆 Imported #21736415 (0x6b46…9976 → 0x949c…25d8)
2024-07-21 01:26:50 💤 Idle (20 peers), best: #21736415 (0x949c…25d8), finalized #21736411 (0x9ee1…3e3c), ⬇ 505.0kiB/s ⬆ 924.5kiB/s
2024-07-21 01:26:54 🏆 Imported #21736416 (0x949c…25d8 → 0xbeb3…1b0d)
2024-07-21 01:26:54 🆕 Imported #21736416 (0x949c…25d8 → 0x6ec0…d4a3)
2024-07-21 01:26:54 🆕 Imported #21736416 (0x949c…25d8 → 0x7c7f…1b7e)
2024-07-21 01:26:55 💤 Idle (19 peers), best: #21736416 (0xbeb3…1b0d), finalized #21736413 (0xe3d3…6193), ⬇ 517.9kiB/s ⬆ 1.1MiB/s

====================

Version: 1.14.0-364961445b7

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: __clone

Thread 'tokio-runtime-worker' panicked at 'SinkImpl::poll_ready called after error.', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/quicksink-0.1.2/src/lib.rs:158

**Comment by bkchr** [comment] 2024-07-21 21:31
Duplicate of https://github.com/paritytech/polkadot-sdk/issues/4934

Please use the search next time. Ty

**Closed by bkchr** 2024-07-21 21:31 UTC
Labels: I10-unconfirmed
