### ISSUE TITLE
Make Beefy work with GRANDPA warp sync

### ISSUE THREAD

**Issue by serban300** [paritytech/polkadot-sdk#2627] opened 2023-12-05 13:19 UTC
We should make it possible to start a node with beefy enabled when using GRANDPA warp sync

**Comment by bkchr** [comment] 2023-12-05 22:09
We currently only use `Grandpa` as provider for the warp sync proofs. For Beefy we probably need to extend the proofs to also include proofs from Beefy. Or better, only use beefy for proofing the warp from state X to state Y.

**Comment by bkchr** [comment] 2023-12-05 22:53
And isn't this a duplicate of https://github.com/paritytech/polkadot-sdk/issues/1118?

**Comment by serban300** [comment] 2023-12-06 08:48
Sorry, I should have added more details in the description. 

Right now if the node is started with `--sync warp` we just disable the BEEFY client. The requirement here is to be able to start a node with BEEFY client + grandpa warp sync. This would mean to wait for GRANDPA warp sync to finish and start the BEEFY client after all the headers have been imported. 

It would be a first step. After that we can implement actual BEEFY warp sync (#1118).

**Comment by bkchr** [comment] 2023-12-06 08:51
> This would mean to wait for GRANDPA warp sync to finish and start the BEEFY client after all the headers have been imported

After all headers from genesis? Why do we need this?

**Comment by serban300** [comment] 2023-12-06 09:37
Because BEEFY tries to walk back from the best finalized header down to BEEFY genesis and then sync all the BEEFY justifications in this range. If headers are missing, it fails. We need to fix this somehow.

**Comment by acatangiu** [comment] 2023-12-06 10:37
> After all headers from genesis? Why do we need this?

To be exact, to initialize BEEFY worker it _currently_ needs headers in backend in range `[max(beefy_genesis_block, best_beefy_finalized_in_aux_db), best_grandpa_finalized]`.

When WarpSyncing there is a "jump" between last sync and current head - GRANDPA gets its mandatory blocks justifications through the `WarpSyncProof` - BEEFY will do the same with #1118 - but before that, we can do a quick fix where BEEFY can walk back the chain over the "jumped" blocks, look at header digests to find out which are mandatory blocks then on-demand request justifications for those.

This ^ should be fairly easy to do and will allow us to remove the "disallow `--sync warp` when BEEFY" limitation.

**Comment by bkchr** [comment] 2023-12-11 12:14
The problem is that gap sync (sync responsible for syncing missing headers/blocks between the warp sync target and genesis) starts syncing from genesis AFAIR. I mean we could probably change this, but right now your quick fix would not work.

**Closed** 2023-12-27 17:18 UTC

**Comment by Polkadot-Forum** [comment] 2024-01-22 11:47
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-kusama-bridge/2971/8

**Comment by Polkadot-Forum** [comment] 2024-04-29 09:01
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/warp-sync-and-beefy/4616/4
