### ISSUE TITLE
Make bridge fees as params of `reserve_transfer_assets`

### ISSUE THREAD

**Issue by yrong** [paritytech/polkadot-sdk#3931] opened 2024-04-02 02:17 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Context

Currently, the bridge/export fee is configured in `BridgeTable` as 
https://github.com/paritytech/polkadot-sdk/blob/52e103784945997cb3808cdfaaf72c468f8fc938/cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs#L867-L870 which will cover all the costs for the export fee in Relay token.  

As Snowbridge is delivering more bridge features(e.g. transfer native token like DOT to Ethereum, transfer WETH back to Ethereum, Call Arbitrary Transact on Ethereum, etc...) each has a different cost,  it does not make sense to be a runtime configuration anymore. Instead, we'd like the fees to be params of the extrinsic `reserve_transfer_assets`.

Another issue is that it's the total cost including the cost of the two hops execution on BridgeHub and on Ethereum. We'd like to separate them as two different fees. For the first hop fee in Relay token and the second hop fee in `WETH`. 

We can provide runtime APIs to calculate fees for each of the hops and it's the prerequisite to remove the [exchange-rate](https://github.com/paritytech/polkadot-sdk/blob/52e103784945997cb3808cdfaaf72c468f8fc938/bridges/snowbridge/pallets/outbound-queue/src/lib.rs#L385) on BH which is another runtime configuration difficult to maintain on chain.

### Request

- Make bridge fees as params of `reserve_transfer_assets` 
- Separate the fee as two hops, for the second hop charge fee in WETH.

### Solution

There is an attempt for the enhancement in https://github.com/Snowfork/polkadot-sdk/pull/132 which could be problematic. Maybe it's better to add another extrinsic into `pallet-xcm` specific for this case as the fee modal here is somehow different from the current implementation.

Meanwhile, notice Parity team is also trying to improve the xcm fee, potential relevant issues/pull requests including:

https://github.com/paritytech/polkadot-sdk/issues/3847

https://github.com/paritytech/polkadot-sdk/issues/690

https://github.com/paritytech/polkadot-sdk/issues/3434

https://github.com/paritytech/polkadot-sdk/pull/3872

We'd suggest taking the use case here into consideration as well.

_No response_

### Are you willing to help with this request?

Yes!

**Comment by acatangiu** [comment] 2024-04-02 08:51
IIUC you would like to add extra fee parameters to `pallet-xcm` extrinsics.
Are there parameters generic or are they bridge-specific?

For better understanding of the request, can you provide an example end-to-end use case and explain the missing pieces/current limitations?

Ideally please provide a proposal for this new extrinsic function signature, what are these new fees params, who calculates them to pass into pallet-xcm, and how is pallet-xcm supposed to use them to fix/support the described e2e use-case.

---

From the high-level understanding I have now, I believe we will not need new fee params once we have https://github.com/paritytech/polkadot-sdk/issues/690 and https://github.com/paritytech/polkadot-sdk/issues/3434. This way you can charge fees along the way from this new `fee_register` that can hold multiple assets.

**Comment by yrong** [comment] 2024-04-02 10:16
Thanks for the information above and good to know that.

I'm not keen on adding a bridge-specific extrinsic, actually in this [PR](https://github.com/Snowfork/polkadot-sdk/pull/132) I attempted to just reuse the current `reserve_transfer_assets` with fee in `WETH`, the main concern is to not force the user to have `WETH` in advance and able to pay all fees in `DOT`, potentially a [swap](https://github.com/Snowfork/polkadot-sdk/blob/7fd2ea43bb13ddf979a228769785b2963f1369b3/substrate/frame/asset-conversion/src/lib.rs#L640) should baked-in on top of the current one.

**Comment by acatangiu** [comment] 2024-04-02 12:31
I still think you should clearly explain here your e2e use-case and limitations encountered. You've referenced some PRs where you tried some solutions, but expecting others to understand the problem by auditing Snowbridge code will yield very little success :)

**Comment by yrong** [comment] 2024-04-02 13:44
Sure! Let me try to be more specific. 

Just as https://github.com/paritytech/polkadot-sdk/issues/3847#issue-2208796132 describes the ideal extrinsic signature is:

```
pub fn transfer_assets(
    origin: OriginFor<T>,
    dest: Box<VersionedLocation>,
    beneficiary: Box<VersionedLocation>,
    assets: Box<VersionedAssets>,
    fees: Box<VersionedAssets>,
    weight_limit: WeightLimit,
) -> DispatchResult;
```

In my case above param `dest` as Ethereum, `assets` as [WETH], `fees` as [DOT, WETH] with `DOT` to pay for the cost on BridgeHub and `WETH` to pay for the cost on Ethereum.

I realize what I've done in my PR is not ideal or even correct, it will cause distraction so please just ignore it.

Let me know if anything more I need to provide.

**Comment by acatangiu** [comment] 2024-04-03 11:11
> Meanwhile, I added a new PR here https://github.com/Snowfork/polkadot-sdk/pull/135 which follows the pattern above.

Thank you! This clears it up significantly 👍 

So what we really need is a way to be able to use **different** assets as _fees_ for different hops along the way.

I am seeing similar issue when thinking about more complex transfers over the P<>K bridge. The problem is we can't (or shouldn't) add dedicated extrinsics to `pallet-xcm` for custom usecases.. E.g. the ethereum_transfer_extrinsic you suggested only works if called on AH, but we'd be adding it to all parachains using `pallet-xcm`. Same with any custom P<>K bridge scenario.

I will think about a more generic solution to both our problems.

**Comment by yrong** [comment] 2024-07-08 15:10
@acatangiu Hey Adrian, any update here?

Seems the runtime api [query_delivery_fees](https://github.com/paritytech/polkadot-sdk/blob/e1460b5ee5f4490b428035aa4a72c1c99a262459/cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L996 ) is already merged, which can be leverged to estimate the delivery cost for the export xcm to remote network like Ethereum.

So based on that is the next step to remove the remote portion from the runtime config [BridgeHubEthereumBaseFee](https://github.com/paritytech/polkadot-sdk/blob/e1460b5ee5f4490b428035aa4a72c1c99a262459/cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs#L634) and make it an user input for the [reserve_transfer_assets](https://github.com/paritytech/polkadot-sdk/blob/e1460b5ee5f4490b428035aa4a72c1c99a262459/polkadot/xcm/pallet-xcm/src/lib.rs#L1008)?

**Comment by acatangiu** [comment] 2024-07-09 09:54
Hey Ron, sorry for the delay in answering here.

The best way to achieve this and many other scenarios using a scalable solution is to use `pallet_xcm::execute()` directly providing your custom/complex asset transfer program(s).

I've also opened https://github.com/paritytech/polkadot-sdk/issues/4736 to create a tool for easier building of these complex/custom asset transfer scenarios.

In the meantime, once runtimes https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.8 are live, they will include:
> Polkadot chains: allow arbitrary XCM execution (https://github.com/polkadot-fellows/runtimes/pull/345)

So you can have the Snowbridge UI build custom XCM programs paying fees in various assets at each hop and directly execute it using `pallet_xcm::execute`.

----

Does this solve your problem? Can we close this PR?

**Closed** 2024-07-09 09:58 UTC
Labels: T6-XCM, I5-enhancement
