### ISSUE TITLE
Finalisation stopped : Encountered error finding best chain

### ISSUE THREAD

**Issue by 1xstj** [paritytech/polkadot-sdk#3487] opened 2024-02-27 10:41 UTC
Finalisation stopped for chain : https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftestnet-rpc-archive.tangle.tools#/explorer

The errors we see on validator nodes after restart is :

```
2024-02-27 10:30:49.726  WARN tokio-runtime-worker grandpa: Encountered error finding best chain containing 0x4c68d1ba9612b87c63d9786547ce706e07080ba7905b6928d8080f0cdd787af4: couldn't find target block: Chain lookup failed: Requested a finality target using a base 0x4c68d1ba9612b87c63d9786547ce706e07080ba7905b6928d8080f0cdd787af4 not in the best chain 0x91c6e5a9de0926428d850503cb76014270190804656fda6d66eb644dbad009e4    
2024-02-27 10:30:49.727  WARN tokio-runtime-worker grandpa: Could not cast prevote: previously known block 0x4c68d1ba9612b87c63d9786547ce706e07080ba7905b6928d8080f0cdd787af4 has disappeared  
```

Telemetry : https://telemetry.polkadot.io/#list/0x3d22af97d919611e03bbcbda96f65988758865423e89b2d99547a6bb61452db3

Substrate version : v1.1.0

Also tried logs with `-lafg` as suggested in other issues, but same output

Logs before restart :
```
2024-02-27 05:42:28.344  INFO tokio-runtime-worker sc_informant: ♻️  Reorg on #651080,0x418d…1743 to #651078,0x5d4a…e6fa, common ancestor #651077,0x9a2d…09f2    
2024-02-27 05:42:28.344  INFO tokio-runtime-worker substrate: ✨ Imported #651078 (0x5d4a…e6fa) 
```

Update:
Restarted validators with `pruning archive` and these are the logs now

```
2024-02-27 11:44:17.838 DEBUG tokio-runtime-worker grandpa: Completed round 2397, state = State { prevote_ghost: Some((0x4c68d1ba9612b87c63d9786547ce706e07080ba7905b6928d8080f0cdd787af4, 651078)), finalized: Some((0x9a2d0c115d0c91876d087a1bf0dc52913b59f1ca9c9f76490d4e26d93a3609f2, 651077)), estimate: Some((0x4c68d1ba9612b87c63d9786547ce706e07080ba7905b6928d8080f0cdd787af4, 651078)), completable: true }, step = None    
2024-02-27 11:44:17.838 DEBUG tokio-runtime-worker grandpa: Round 2397: prevotes: 534/500/749 weight, 534/749 actual    
2024-02-27 11:44:17.838 DEBUG tokio-runtime-worker grandpa: Round 2397: precommits: 534/500/749 weight, 534/749 actual  
```

**Comment by 1xstj** [comment] 2024-02-27 17:09
Fixed by calling grandpa.noteStalled

**Comment by dmitrylavrenov** [comment] 2024-07-01 11:02
Hey @1xstj,

Have you got the root cause of this behaviour ? Which substrate version has been used in your testnet ?

We've faced the same issue few days ago on our humanode.io mainnet  and would like to get the root cause. `grandpa.noteStalled` has helped to continue finalization. But I don't think it's the fix. 

@bkchr @davxy What do you think about this case ? Can you suggest smth to investigate the issue ? We would like to hear some thought from you, please.

**Comment by bkchr** [comment] 2024-07-01 12:54
There is probably no easy fix for this. I can not recommend anything. If this is happening more often, it would be nice to find out how and why grandpa is voting this way, maybe it reveals the bug or not.

**Comment by dmitrylavrenov** [comment] 2024-07-01 13:04
> There is probably no easy fix for this. I can not recommend anything. If this is happening more often, it would be nice to find out how and why grandpa is voting this way, maybe it reveals the bug or not.

Got it,

Anyway, I've analyzed reorg logs and found smth interesting, would like to know if it makes sense.
The guys and our node has reorg to 2 blocks back. As a result, we got the situation of voting error that block has been disappeared. 

The rest reorg logs contains the info, that reorg happens on the same block or 1 block forward. But not to the past.

**Comment by MOZGIII** [comment] 2024-07-26 09:05
The problem now occurs daily.
https://github.com/humanode-network/humanode/issues/1104 - tracking issue
Please reopen, or should we start another issue here for this?

I invite parity team to look into this stuff on our end now - cause it seems like it will affect everyone at some point

**Comment by dmitrylavrenov** [comment] 2024-07-26 09:49
@bkchr @davxy implemented an test that reproduce faced issue - https://github.com/humanode-network/humanode/issues/1104#issuecomment-2252375673.

**Closed** 2024-07-28 20:51 UTC
Labels: I10-unconfirmed
