### ISSUE TITLE
async backing: lots of peers banned for invalid AttestedCandidateRequest

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#1426] opened 2023-09-06 13:25 UTC
We seem to have a check before answering the request that verifies the manifest was sent to the peer before. The check fails and this might be a distribution bug.

```
Report 12D3KooWQcTHknzKXb7XCMHJYecWRx9jH2XYHVUzk2ythSez6W77: -300000 to -1761216939. Reason: Unexpected attested candidate request. Banned, disconnecting.    
```

https://grafana.teleport.parity.io/goto/FmpwRUkIg?orgId=1

**Comment by rphmeier** [comment] 2023-09-07 00:11
It's not just unexpected candidate requests, but also a lot of unexpected statements and unexpected manifests and unexpected acknowledgements.

Something is wrong with either the grid tracker or the authority discovery.

**Comment by eskimor** [comment] 2023-10-20 19:04
@sandreim is this resolved already?

**Comment by alexggh** [comment] 2023-11-10 09:19
## Initial issue
I did some spelunking here overall I think this issue has been resolved with https://github.com/paritytech/polkadot-sdk/commit/a46183c706e300b1993f28278a273153010d2b0c, exposing the reasons why I think this got fixed.

1. Fixes to the statement-distribution topology have been done in the same commit here  https://github.com/paritytech/polkadot-sdk/commit/a46183c706e300b1993f28278a273153010d2b0c
2. I did some bisecting here and on a network with 20 validators and 3 parachains, this issue starting reproducing in a few hours, [logs](https://grafana.teleport.parity.io/goto/yaHdj34IR?orgId=1).
- [NOK] 3706a75f - reproduced in a few hours of running on versi.
- [NOK] 76994356fc - reproduced in a few hours of running on versi.
- [OK] a46183c706 - Issue did not appear after running over 12h

I don't fully understand the reasons this reproduces in the first place, so we might be just lucky with a46183c706, but given it fixes the place where this error pops-up I find it unlikely.  I'm going to run latest master for another 12h, if it still doesn't reproduce we can concur that this issue that emits `Reason: Unexpected attested candidate request. Banned, disconnecting.`  got fixed.


## Current problems

Now, it seems that there is some adjacent issue that was observed during testing by @alindima when testing https://github.com/paritytech/polkadot-sdk/pull/2046, [logs](https://grafana.teleport.parity.io/goto/7vl7R6VIg?orgId=1)
```
Reduce reputation peer=PeerId("12D3KooWP2LGsamcPoNV25GsH3FVUzGmYsTtDkop7tbmvREppqyU") rep=CostMinor("Unexpected Statement")
```

It doesn't seem to be the same problem and not the same severity, since the node doesn't get disconnected it just gets a small reputation update, but it is a problem nonetheless, I'll try root-causing it as well.

**Comment by alexggh** [comment] 2023-11-15 13:45
Closing this issue, as the original issue does not reproduce anymore, opened a separate one for https://github.com/paritytech/polkadot-sdk/issues/2346, but that's more of annoyance that an actual bug, since the node will behave correctly, without disconnect its peers..

**Closed by alexggh** 2023-11-15 13:45 UTC
Labels: I2-bug
