### ISSUE TITLE
`chain-spec-builder` for parachain missing `relay_chain` field

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#5295] opened 2024-08-08 21:52 UTC
How can you use `chain-spec-builder` to compose a chain spec for a parachain compatible with a relay chain / zombienet.

For example, end to end scenario for the Polkadot SDK Parachain Template:

```
chain-spec-builder create --runtime-wasm-path ./target/release/wbuild/parachain-template-runtime/parachain_template_runtime.compact.wasm default
```

```
zombienet --provider native spawn zombienet.toml  
```

We get the error:

```
Error:           Error: Command failed with exit code 1: bash -c polkadot-parachain build-spec  --disable-default-bootnode --chain /var/folders/_1/q03733qd0pv42n1dvkcvyx0c0000gn/T/zombie-c6f2f0a963e7ba0fbd8d9c1f23f3a055_-8299-CuFS1I4z9SQ0/1004-rococo-local-plain.json  --raw > /var/folders/_1/q03733qd0pv42n1dvkcvyx0c0000gn/T/zombie-c6f2f0a963e7ba0fbd8d9c1f23f3a055_-8299-CuFS1I4z9SQ0/1004-rococo-local-raw.json
Error: Input("Error parsing spec file: missing field `relay_chain` at line 69 column 1")
```

So it is missing fields. Also the `para_id` field.

When looking at the `polkadot-sdk` repo, it seems that this `relay_chain` field is getting injected via shell scripts.... is this the expectation of what we should do?

**Comment by shawntabrizi** [comment] 2024-08-08 21:56
Perhaps the solution is to add some additional fields to `chain-spec-builder` allowing us to inject these fields.

If so, I am open to taking on this issue.

**Comment by skunert** [comment] 2024-08-09 07:55
Yes that is a bit annoying currently, but probably soon fixed!

This is a duplicate of https://github.com/paritytech/polkadot-sdk/issues/4873
There is a fix in the works: https://github.com/paritytech/polkadot-sdk/pull/4889

**Closed by skunert** 2024-08-09 07:55 UTC

**Comment by pepoviola** [comment] 2024-08-09 08:41
Hey @shawntabrizi / @skunert, just a small note here. Currently we are not using the `chain-spec-builder` as part of zombienet and we will need to integrate in the existing flow. I can work on that (and fill the missing fields internally) or wait for #4889 (with the missing fields issue resolved).

Thanks!

**Comment by michalkucharczyk** [comment] 2024-09-04 11:04
Shall be fixed now in: https://github.com/paritytech/polkadot-sdk/pull/4889

**Comment by shawntabrizi** [comment] 2024-09-05 14:56
great, ill give it a try soon in my scenarios
