### ISSUE TITLE
StateStrategy assumes all the state (of a block) fits into RAM

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/polkadot-sdk#4608] opened 2024-05-28 03:43 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Reading through source code now that we started (ab)using `StateStrategy` for our sync implementation I noticed that it has an implicit assumption that the whole state as of any particular block can be assembled in RAM (not even accounting for other things that might be in RAM at the same time), which is naive and potentially problematic once state grows beyond size that fits in RAM.

### Request

I think there should be some kind of fallback that stores downloaded state in auxiliary store on disk or similar instead of RAM. Maybe it should even be the default way to store state so two options don't need to be supported. This will have an impact on block import/application enums/APIs as well.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by bkchr** [comment] 2024-05-28 09:47
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/4

**Closed by bkchr** 2024-05-28 09:47 UTC
Labels: I5-enhancement
