### ISSUE TITLE
Fresh system-chain sync is stuck

### ISSUE THREAD

**Issue by tugytur** [paritytech/polkadot-sdk#4648] opened 2024-05-30 11:27 UTC
When doing a fresh archive sync of any of the system chains the finalized block always stays at 0.
I also did a fresh sync for a relay chain (westend) and there it works.

Throughout the sync `finalized` stays at 0, when `best` reaches `target` the node switches to `Preparing` and does 0.0 bps for hours. Nothing happens. As a Workaround I downgraded to v 1.11 when it caught up and then it finalized and upgraded back to the latest release.

Flags used:
```
ExecStart=/usr/local/bin/polkadot-parachain \
        --name="corksm1" \
        --database=paritydb \
        --state-pruning=archive \
        --blocks-pruning=archive \
        --base-path=/var/blockchain/data \
        --keystore-path=/var/blockchain/keystore \
        --chain=coretime-kusama \
        --no-mdns \
        --no-hardware-benchmarks \
        --prometheus-port=9615 \
        --rpc-port=9944 \
        --in-peers-light=20 \
        --no-telemetry \
        --rpc-external \
        --listen-addr=/ip4/0.0.0.0/tcp/30012/ws \
        --listen-addr=/ip4/0.0.0.0/tcp/30013 \
        --rpc-max-connections=10000 \
        --rpc-max-request-size=1 \
        --rpc-max-response-size=15 \
        --rpc-max-subscriptions-per-connection=1024 \
        --rpc-methods=safe \
        --rpc-cors=all \
        --wasm-execution=compiled \
        --max-runtime-instances=32 \
        --runtime-cache-size=64 \
        --enable-offchain-indexing=true \
        --relay-chain-rpc-urls="ws://10.10.152.11:9944" \
        --relay-chain-rpc-urls="ws://10.10.152.12:9944" \
        -- \
        --no-telemetry \
        --no-mdns \
        --no-hardware-benchmarks \
        --no-prometheus \
        --listen-addr=/ip4/0.0.0.0/tcp/30334 \
        --in-peers=0 \
        --out-peers=0 \
        --in-peers-light=0
```

**Comment by AdsRose** [comment] 2024-05-31 07:41
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by skunert** [comment] 2024-06-05 18:00
Closing since this is a duplicate of #4614

**Closed by skunert** 2024-06-05 18:00 UTC
