### ISSUE TITLE
IntelliJ Rust plugin can't build runtime

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/polkadot-sdk#6247] opened 2024-10-26 19:50 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I'm getting the following confusing error:

<details>

```
error: failed to run custom build command for `pallet-revive-fixtures v0.1.0 (/web/subspace/polkadot-sdk/substrate/frame/revive/fixtures)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/home/nazar-pc/.cache/cargo/target/debug/build/pallet-revive-fixtures-aff745ce5f9ef36b/build-script-build` (exit status: 1)
  --- stdout
  cargo::rerun-if-changed=/web/subspace/polkadot-sdk/substrate/frame/revive/fixtures
  cargo::rerun-if-changed=/web/subspace/polkadot-sdk/substrate/frame/revive/uapi
  --- stderr
      Updating crates.io index
       Locking 13 packages to latest compatible versions
        Adding bitflags v1.3.2 (latest: v2.6.0)
    Downloaded polkavm-derive v0.13.0
    Downloaded polkavm-derive-impl-macro v0.13.0
    Downloaded polkavm-derive-impl v0.13.0
  error: "/home/nazar-pc/.rustup/toolchains/rve-nightly/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
          rustup component add rust-src --toolchain rve-nightly
  Error: Failed to build contracts
  Stack backtrace:
     0: anyhow::error::<impl anyhow::Error>::msg
     1: anyhow::__private::format_err
     2: build_script_build::build::invoke_build
     3: build_script_build::build::run
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
     6: std::sys::backtrace::__rust_begin_short_backtrace
     7: std::rt::lang_start::{{closure}}
     8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:284:13
     9: std::panicking::try::do_call
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
    10: std::panicking::try
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
    11: std::panic::catch_unwind
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
    12: std::rt::lang_start_internal::{{closure}}
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:48
    13: std::panicking::try::do_call
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
    14: std::panicking::try
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
    15: std::panic::catch_unwind
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
    16: std::rt::lang_start_internal
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:20
    17: std::rt::lang_start
    18: main
    19: __libc_start_call_main
               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    20: __libc_start_main_impl
               at ./csu/../csu/libc-start.c:360:3
    21: _start
```

</details>

The lock file exists for me, but at `/home/nazar-pc/.rustup/toolchains/rve-nightly/lib/rustlib/src/rust/Cargo.lock` instead. Not sure why it is searching for lock file at the wrong location.

I have `rve-nightly` 1.1.0 installed.

**Comment by acatangiu** [comment] 2024-10-28 08:05
cc @pgherveou @xermicus

**Comment by JuaniRios** [comment] 2024-10-29 12:37
Have the same problem

**Comment by ggwpez** [comment] 2024-10-29 13:06
Is that enabling all features by any chance? Enabling the RISCV feature will cause it to fail compiling, since you probably dont have that toolchain.

**Comment by nazar-pc** [comment] 2024-10-29 13:07
I do have the toolchain though, see `rve-nightly` in the original message, is that not it?

**Comment by nazar-pc** [comment] 2024-10-29 13:18
Just opening project in IDE, it tries to build and analyze everything and fails. Have not tried the mentioned PR and working on something else at the moment.

**Comment by xermicus** [comment] 2024-10-29 13:23
#6266 will fix this.

What exactly are you trying to do? The custom toolchain is only required for developing the `revive` pallet. A correct configuration shouldn't pass the `riscv` feature around.

**Comment by xermicus** [comment] 2024-10-29 13:33
Ah okay, my web UI didn't reload above comments :sweat_smile:

Yeah this used to work but broke for some reason. I can repro locally, but #6266 will fix it.

**Comment by athei** [comment] 2024-10-29 14:57
Did intellij worked for you properly before? In my experience it never worked really well on that repo. Not saying we should not resolve this issue. But probably something else will pop up after fixing it.

**Comment by nazar-pc** [comment] 2024-10-29 15:11
It worked in the past and other than this still works.

At the same time there are some annoying things about how this repo is maintained, so I have to use environment variables to set one toolchain version for checking the code and another for formatting purposes. And https://github.com/paritytech/polkadot-sdk/pull/5317 that would fix at least one half of that is yet to be merged.

**Comment by athei** [comment] 2024-10-31 13:16
Should be fixed by https://github.com/paritytech/polkadot-sdk/pull/6305

Can you confirm?

**Comment by nazar-pc** [comment] 2024-10-31 13:30
Actually no, at very least it complains about `-Z` only available on nightly compiler, while the repo is supposed to be built with a stable compiler.

**Comment by athei** [comment] 2024-10-31 13:33
This is why we setting this:
https://github.com/paritytech/polkadot-sdk/blob/dd9924fad0cd9314f21eff621208dc2ec60e0cf5/substrate/frame/revive/fixtures/build.rs#L121

Building this with cargo works. It seems that intellij is ignoring this somehow. Or it prefilters the CLI args and comes to the conclusion that it won't work when in fact it actually does.

I suggest setting a nightly toolchain in intellij to fix that. Or file a bug with them.

**Comment by nazar-pc** [comment] 2024-10-31 14:06
> This is why we setting this:

That is a dirty hack, no one except Rustc itself should really use `RUSTC_BOOTSTRAP=1`. I believe it is also not guaranteed to be stable by any means, so might compile with one "stable" version and not compile with another.

> I suggest setting a nightly toolchain in intellij to fix that

I wish I could, but then I get lots of false-positive from additional clippy lints triggered on Substrate codebase all over the place and when I run `cargo clippy` in the terminal it'll be recompiling everything from scratch after IDE compiled things with a different toolchain.

It is really a huge pain to work with for contributors without `rust-toolchain.toml` in the repo.

Here is what IDE spits out:

<details>

```
error: failed to run custom build command for `sc-runtime-test v2.0.0 (/web/subspace/polkadot-sdk/substrate/client/executor/runtime-test)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/home/nazar-pc/.cache/cargo/target/debug/build/sc-runtime-test-6b0fe188e2cd6525/build-script-build` (exit status: 1)
  --- stdout
  cargo:warning=Could not find `Cargo.lock` for `/web/subspace/polkadot-sdk/substrate/client/executor/runtime-test/Cargo.toml`, while searching from `/home/nazar-pc/.cache/cargo/target/debug/build/sc-runtime-test-7d6304c2b671cf30/out`. To fix this, point the `WASM_BUILD_WORKSPACE_HINT` env variable to the directory of the workspace being compiled.
  cargo:warning=Could not find `Cargo.lock` for `/web/subspace/polkadot-sdk/substrate/client/executor/runtime-test/Cargo.toml`, while searching from `/home/nazar-pc/.cache/cargo/target/debug/build/sc-runtime-test-7d6304c2b671cf30/out`. To fix this, point the `WASM_BUILD_WORKSPACE_HINT` env variable to the directory of the workspace being compiled.
  Information that should be included in a bug report.
  Executing build command: env -u CARGO_ENCODED_RUSTFLAGS -u RUSTC CARGO_MAKEFLAGS="-j --jobserver-fds=8,9 --jobserver-auth=8,9" CARGO_TARGET_DIR="/home/nazar-pc/.cache/cargo/target/debug/wbuild/sc-runtime-test/target" RUSTC_BOOTSTRAP="1" RUSTFLAGS="-C target-cpu=mvp -C target-feature=-sign-ext -C link-arg=--export-table -Clink-arg=--export=__heap_base -C link-arg=--import-memory  --cfg substrate_runtime " SKIP_WASM_BUILD="" "/home/nazar-pc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/home/nazar-pc/.cache/cargo/target/debug/wbuild/sc-runtime-test/Cargo.toml" "--color=always" "--profile" "release" "-Z" "build-std"
  Using rustc version: rustc 1.82.0 (f6e511eec 2024-10-15)
  --- stderr
```

</details>

**Comment by athei** [comment] 2024-10-31 14:36
> That is a dirty hack, no one except Rustc itself should really use `RUSTC_BOOTSTRAP=1`. I believe it is also not guaranteed to be stable by any means, so might compile with one "stable" version and not compile with another.

So is using a nightly toolchain. We are using an unstable feature. Of course it doesn't get stable by using a stable toolchain. However, it improves the experience as people don't need to install an additional toolchain.

> It is really a huge pain to work with for contributors without rust-toolchain.toml in the repo.

This rust-toolchain.toml would need to contain a nightly toolchain, though.

**Comment by pgherveou** [comment] 2024-10-31 15:37
@nazar-pc 
did you try what is suggested by the error message here
  
```
error: "/home/nazar-pc/.rustup/toolchains/rve-nightly/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
          rustup component add rust-src --toolchain rve-nightly
  Error: Failed to build contracts
```

**Comment by athei** [comment] 2024-10-31 15:38
Nahh. We are building with the toolchain used to build the crate now. So the `rust-src` component has to be installed for that.

**Comment by nazar-pc** [comment] 2024-10-31 15:44
> did you try what is suggested by the error message here

As I wrote in the very first message, it was already installed

**Comment by athei** [comment] 2024-10-31 16:06
Are you sure? You only state the rve-nightly toolchain is installed. What we ask you to do is to install `rust-src` for whatever toolchain you are building the workspace with.

**Comment by nazar-pc** [comment] 2024-10-31 16:18
I do have `rust-src` component installed as well (which `rust-toolchain.toml` https://github.com/paritytech/polkadot-sdk/pull/5317 would ensure as well)

**Comment by nazar-pc** [comment] 2024-11-04 17:02
On latest `master` regular build in CLI with `cargo +1.81.0 check --all-targets --workspace` now fails too:
```
error: failed to run custom build command for `pallet-revive-fixtures v0.1.0 (/web/subspace/polkadot-sdk/substrate/frame/revive/fixtures)`

Caused by:
  process didn't exit successfully: `/home/nazar-pc/.cache/cargo/target/debug/build/pallet-revive-fixtures-4243b16f4f2a1323/build-script-build` (exit status: 1)
  --- stdout
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_STRIP
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_OPTIMIZE
  cargo::rerun-if-changed=/web/subspace/polkadot-sdk/substrate/frame/revive/fixtures
  cargo::rerun-if-changed=/web/subspace/polkadot-sdk/substrate/frame/revive/uapi

  --- stderr
      Updating crates.io index
       Locking 13 packages to latest compatible versions
        Adding bitflags v1.3.2 (latest: v2.6.0)
   Downloading crates ...
    Downloaded syn v2.0.87
  error: "/home/nazar-pc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
          rustup component add rust-src

  Error: Failed to build contracts
```

Two problems here.

Wrong lock file path:
```diff
-.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock
+.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/Cargo.lock
```

The path used is actually correct for 1.81.0, but not for 1.82.0 (current stable).

The reason it has the wrong path is likely related to the fact that if you look closely it is `stable`, not `1.81.0` that I specified for `cargo` explicitly, so it only really works properly in CI or environments where it is configured as the only (default?) version. I think fixing it will fix the issue here.

**Comment by athei** [comment] 2024-11-05 08:06
So you think what is going wrong is that the build.rs is selecting stable instead of 1.81 as it should? If this is true it should be fixed by adding `rust-src` to 1.81? Can you try? Will still need to fix the version selection. This is  just to confirm.

**Comment by athei** [comment] 2024-11-05 11:25
I am trying to reproduce and fix that.

**Comment by athei** [comment] 2024-11-05 11:54
Should be fixed by: https://github.com/paritytech/polkadot-sdk/pull/6365

**Comment by athei** [comment] 2024-11-05 18:39
Can you confirm if your problem if fixed?

**Comment by nazar-pc** [comment] 2024-11-05 19:00
Building with CLI is fixed indeed, but IDE is still broken. Here is full log with everything IDE does and how:
[intellij-rust.log](https://github.com/user-attachments/files/17637228/intellij-rust.log)

**Comment by athei** [comment] 2024-11-05 21:12
As said before: We can't fix it on our end. Intellij seems to ignore `RUSTC_BOOSTRAP` and requires a nightly toolchain. You can probably fix it on your end by setting a nightly toolchain for your polkadot-sdk. Or by just selecting a nightly toolchain for intellij.

**Closed** 2024-11-05 21:46 UTC
Labels: I2-bug, I10-unconfirmed
