### ISSUE TITLE
Enhance WarpSync zombienet tests with BEEFY validations

### ISSUE THREAD

**Issue by acatangiu** [paritytech/polkadot-sdk#2787] opened 2023-12-22 07:40 UTC
BEEFY + (GRANDPA) WarpSync was enabled in https://github.com/paritytech/polkadot-sdk/pull/2689

Add zombienet Warp Sync regression tests (needs rebuilding db used in existing zombienet tests to include BEEFY state)

Done:
- [x] Added BEEFY support to kitchensink
- [x] Published [PR](https://github.com/paritytech/polkadot-sdk/pull/2854) that adds some basic BEEFY checks to the warp sync tests

Summarizing remaining work:

- [x] investigate the issue with `0002-validators-warp-sync` where BEEFY doesn't catch-up.
- [x] investigate this comment: https://github.com/paritytech/polkadot-sdk/pull/2854#discussion_r1447343237 => not needed anymore. It's related to https://github.com/paritytech/polkadot-sdk/issues/2568

**Comment by serban300** [comment] 2024-01-03 13:19
Experimented with multiple solutions. No matter what, we need a pretty big database (>50k blocks) in order to make sure that the headers sync doesn't finish before BEEFY starts. Otherwise the test wouldn't cover much.

I think the best strategy would be to generate a rococo-local database with > 50k blocks and with an epoch duration that isn't too small (for example 30-60 min) in order to make sure that BEEFY catches up fast with the chain.

Started a zombienet with this strategy. Will need to leave it running for a couple of days in order to generate a big enough db.

**Comment by serban300** [comment] 2024-01-09 08:56
Added BEEFY support to the kitchensink runtime. Now trying to extend the current warp sync tests (which were also built using the kitchensink runtime) with BEEFY. 

Generated a couple of snapshots and experimenting with them. Most of the tests work. Just having some issues with `0002-validators-warp-sync` where the chain doesn't finalize blocks if I start it from my snapshots, or sometimes bob doesn't even warp sync (it gets stuck with 0 peers - all peers refuse the connection). Not sure if it's something related to the way I generate the snapshots. Investigating.

**Comment by serban300** [comment] 2024-01-10 11:17
Found the cause of the issue where for `0002-validators-warp-sync` the chain doesn't finalize blocks, or doesn't warp sync. We need to generate the snapshot using `--state-pruning archive --blocks-pruning archive`. But still for `0002-validators-warp-sync` BEEFY doesn't catch-up.

I will shortly publish a PR that adds some basic BEEFY checks to the warp sync tests first. And I would like to investigate the remaining issue related to `0002-validators-warp-sync` separately.

**Comment by serban300** [comment] 2024-01-15 10:01
The issue with `0002-validators-warp-sync` was fixed by https://github.com/paritytech/polkadot-sdk/pull/2919

Regenerating the DB snapshot on top of that fix in https://github.com/paritytech/polkadot-sdk/pull/2928

**Closed** 2024-01-15 11:42 UTC
Labels: T10-tests
