### ISSUE TITLE
Improve transaction handling for Parachains

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#1202] opened 2023-08-28 08:42 UTC
The transaction pool is designed to send out events about `inclusion` of a transaction in a block when the transaction got included in a block that is seen as best block of the local node. If this block then for example is removed from the best chain (because we forked), a `retracted` event is sent. On parachains a block at the tip of the chain isn't imported as best block. Setting the best block happens asynchronously as it depends on what is the best relay chain block and which parachain block got included in this relay chain block. This means that instead of waiting ~6 seconds on the relay chain we have to wait at least 12 seconds on a Parachain. 

To improve the situation we should directly send the `inclusion` event when the transaction appears in any block. It should not be important if the block is a best block or not. I also don't see any real benefit in sending a `retracted` event (we should check the new RPC spec, but I doubt that it is still send there) and we should be able to omit it.

**Comment by bkchr** [comment] 2023-08-31 08:11
This change is also important to have [`ready_at`](https://github.com/paritytech/polkadot-sdk/blob/5da00e68780dc28bdf0f08a0971ee22e5b223079/substrate/client/transaction-pool/src/lib.rs#L330) return directly when we build a new block. Currently we don't start the maintenance as we don't have seen the block import yet. A consequence of running maintenance for every block could be that we invalidate transactions on one fork, but they are not yet included in another fork. I don't think that the transaction pool currently supports "fork handling". We should look into this when working on this feature.

**Comment by rphmeier** [comment] 2023-09-04 20:00
It's also worth noting that collators will build forks deliberately, if there are relay chain forks.

And now, with asynchronous backing, may build on top of blocks which themselves aren't the best (and sometimes multiple blocks immediately in a row).

I'm not really familiar with the details of the transaction pool but it sounds like the solution here should work for those requirements as well.

**Comment by michalkucharczyk** [comment] 2023-09-11 18:33
> (we should check the new RPC spec, but I doubt that it is still send there)

Forgive dumb question, where is new spec? Is it [here](https://github.com/paritytech/polkadot-sdk/blob/2c8021f998a4b3f3e9c0416c7886ef05803aba9d/substrate/client/rpc-spec-v2/) and [here](https://github.com/paritytech/json-rpc-interface-spec)?

**Comment by bkchr** [comment] 2023-09-11 21:53
Yes this is the new spec. I already opened a proper issue here: https://github.com/paritytech/json-rpc-interface-spec/issues/87

**Comment by bkchr** [comment] 2023-11-09 13:00
While looking into async backing we have seen that the transaction pool is sometimes rejecting transactions when building a fork. Let's assume you build block `X` that includes two transactions from account `A`. After having build the block and removing the transactions of block `X` from the tx pool, we start building block `X'` (a fork of `X`). Account `A` still has some transactions in the tx pool, but their nonce doesn't match the chain state of `Y` (parent of `X` and `X'`) as the tx pool thinks that we already included the transactions. While the tx pool is right that we already have included them in a block, we actually have done this in a fork and thus the assumption isn't correct and will lead to `apply_extrinsic` returning ` Error::Future` (because the nonce is too high). 

To solve this issue we need to make the transaction pool fork aware. This means that if we are building `X` or `X'`, we both times use the transaction that are valid in the view of `Y`.

**Comment by bkchr** [comment] 2023-11-09 19:48
@bernardoaraujor please run with `-ltxpool=trace` and check why the transactions are removed.

**Comment by bkchr** [comment] 2023-11-09 23:00
Looks exactly like the issue I described above. You are building a fork and then you include some transaction with a future nonce. This leads then to all its descendants being removed as well. You could for example not have transaction that depend on each other (by the nonce) and then you would not see this issue.

**Comment by ggwpez** [comment] 2023-11-09 23:33
So if you use the sTPS tool then it should not happen, or? Since that is never re-using accounts.

**Comment by bkchr** [comment] 2023-11-10 12:46
Yes

**Comment by bkchr** [comment] 2024-02-05 11:45
@michalkucharczyk could you give some short update on your status?

**Comment by bkchr** [comment] 2024-02-05 12:05
Thank you! :)

**Comment by Polkadot-Forum** [comment] 2024-03-08 08:09
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/parity-tech-update-for-february/6630/1

**Comment by michalkucharczyk** [comment] 2024-04-04 19:07
Quick update for now:
1. I have working fork-aware txpool crate with (hopefully) most of the scenarios tested on unit-test level,
1. Some pieces are missing though (main points from my todo list): 
    - obeying txpool size limits, 
    - properly handling finalization stalls (should not be difficult, but I need to think about this), 
    - re-check metrics sent out, probably adjust them with some forks-handling-related stats, 
    - check if there is any performance regression (also during warp-sync),
1. Need to integrate this work with the _client_, do some basic and stress-tests with stps tool to check if problems are gone,
1. Some memory optimizations needs to be done (I have excessive clones which I want to get rid of),
1. Probably validation cache may be needed (but I need to measure it),

I'll try to focus on opening the PR that would allow to do some preliminary testing and at least check if the original problems are solved with this. Obviously not all of the above steps needs to be accomplished to allow this. I still need some time (days) to do it.

**Comment by bkchr** [comment] 2024-04-04 19:35
> with referenda [#374](https://kusama.polkassembly.io/referenda/374) on Kusama, we are ready to get to 6s block time on Moonriver, but this issue is a blocker, can you share an update on this one @michalkucharczyk please?

This bug should already appear without async backing. How do you want to approach async backing? Will you change your slot time to 6s or will you use the unincluded segment and stay with 12s slot time? If you go to 6s, this txpool behavior should not change.

**Comment by girazoki** [comment] 2024-04-19 15:03
> > with referenda [#374](https://kusama.polkassembly.io/referenda/374) on Kusama, we are ready to get to 6s block time on Moonriver, but this issue is a blocker, can you share an update on this one @michalkucharczyk please?
> 
> This bug should already appear without async backing. How do you want to approach async backing? Will you change your slot time to 6s or will you use the unincluded segment and stay with 12s slot time? If you go to 6s, this txpool behavior should not change.

Hey @bkchr , you mean that if we use a 6 second slot we should not see this bug in the tx-pool? I agree that this happens even without asynchronous backing, we are suffering this currently and we still did not reduce the slot time to 6s

**Comment by bkchr** [comment] 2024-04-21 20:21
> you mean that if we use a 6 second slot we should not see this bug in the tx-pool?

No, you will still have this issue, but it should not change to what you see right now. However, if you stay at 12s and use unincluded segment of 2, it may gets worse. I mean the underlying issue is the same, but you may include more tx and thus others are failing etc.

Generally this issue probably only appears in production networks if someone is "spamming" the tx pool. For sure someone could be unlucky, but you also got multiple collators and thus, they may get included by someone else.

**Comment by wilwade** [comment] 2024-04-21 21:27
> if someone is "spamming" the tx pool.

At least on Frequency that focuses on companies instead of end users interacting with the chain, dumping a lot of transactions onto the chain at once (aka "spamming") is a fairly common use case.

**Comment by bkchr** [comment] 2024-04-22 19:37
I mean this should not be a complaint and I clearly did not thought about all the possibilities :see_no_evil: 

@wilwade do you see this being a big problem in the "wild"? How many collators do you have running?

**Comment by bkchr** [comment] 2024-04-22 19:57
Just for myself and anyone that is interested, writing down here some information:

This issue actually exists in two ways:

1. For some time we included parachain blocks without setting them directly as best block and instead waited for the relay chain to have them backed and then set them as best block. The problem with this is that we did not execute the maintenance for non best blocks. Thus we build `X + 1` probably on the same set of transactions as `X`. When you find an invalid transaction we automatically remove the entire subtree. The case described here should actually not happen anymore since [this commit](https://github.com/paritytech/polkadot-sdk/commit/b25d29a50247f284cde5b24e270b6db7b4a81e7e), because we now set the best block directly and maintenance is running.
2. The second case is actually if maintenance is running because we set the best block. We will remove transactions that got included in a block. The special case now for parachains is that their block production is mainly driven by relay chain block import. This means that if you import a relay chain fork, the same node will produce multiple parachain blocks on the same height and then [this](https://github.com/paritytech/polkadot-sdk/issues/1202#issuecomment-1803786956) happens.

Leaving this here for future me and others :D

**Comment by wilwade** [comment] 2024-04-23 15:50
@bkchr 

We have caught it on our Testnet (Paseo based) with just two collators + one RPC (all peering). Have had a hard time recreating consistently however.

Haven't seen it in mainnet yet to my knowledge, however, we might not hear about it and the slamming we do on testnet isn't yet happening on mainnet as much (coming in the next few weeks).

**Comment by makinghappen** [comment] 2024-04-27 11:53
any chance for this to be fixed soon?

**Comment by michalkucharczyk** [comment] 2024-04-29 09:51
> any chance for this to be fixed soon?

Still in progress.

**Comment by Polkadot-Forum** [comment] 2024-05-01 07:32
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/paritytech-update-for-april/7646/1

**Comment by girazoki** [comment] 2024-05-13 08:43
@michalkucharczyk @bkchr is there any news on this? This feels quite important for chains that have a low number of collators (e.g., what we expect for parathreads for instance)

**Comment by girazoki** [comment] 2024-05-14 07:25
Related to this issue, is there anything we can tweak in the parameters of an  internal relay (based of fast-rococo) so that we see less often re-orgs?

**Comment by skunert** [comment] 2024-05-14 07:57
> Related to this issue, is there anything we can tweak in the parameters of an internal relay (based of fast-rococo) so that we see less often re-orgs?

I think there is nothing you can do about this. Fast-rococo has a low session duration and we do not choose unincluded parents in the parachain that have a relay parent in the last session. So once the session changes you will start building on the included block again, which will cause a fork.

**Comment by michalkucharczyk** [comment] 2024-05-14 21:58
> @michalkucharczyk @bkchr is there any news on this? This feels quite important for chains that have a low number of collators (e.g., what we expect for parathreads for instance)

The work is still in progress, I am now doing some stress tests, and will be opening the PR soon.

**Comment by michalkucharczyk** [comment] 2024-05-24 06:50
Status update: I have a working implementation. My plan is to add a new command line parameter:
```
      --pool-type <POOL_TYPE>
          The type of transaction pool to be instantiated

          [default: single-state]

          Possible values:
          - single-state: Uses a legacy, single-state transaction pool
          - fork-aware:   Uses a fork-aware transaction pool
```

This would allow for some transitioning period during which I can further stabilize and likely do some bugs fixing before we do a switch to fork-aware transaction pool. 
To make review smoother and easier I split my into two parts:
- refactoring `sc-transcation-pool` crate crate and allowing to use transaction pool trait object across the codebase (#4561),
- addition fork-aware txpool into `sc-transcation-pool` crate. The PR will be opened once ground work is reviewed/accepted and merged.

**Comment by albertov19** [comment] 2024-06-12 09:59
Hey @michalkucharczyk  - Any updates? Thanks in advance

**Comment by NZT48** [comment] 2024-08-05 14:57
I would like to add on this issue that we experienced two issues on NeuroWeb that look related to this.

First issue is same as in issues that @brenzi mentioned (https://substrate.stackexchange.com/questions/11225/pending-extrinsics-jammed-how-to-ensure-re-broadcast). We saw on our Devnet (internal network), transactions were not reaching our collators, while they are in the non-collator nodes tx-pool. It can be seen below that all nodes except collators are having 600+ transactions in pool.
 ![Screenshot 2024-08-05 at 11 49 42](https://github.com/user-attachments/assets/f4adad7b-e24d-4037-8fba-8adf8cd2be64)

What we understood is it that temporary solution for this is to have on collator restarted every 5 minutes by cron job. Until #4639 is merged and released.

Second issue, we are looking for some confirmation that is related to this one and help in resolving. After runtime upgrade where we changed dependencies from v0.9.40 to v1.9.0 (https://github.com/OriginTrail/neuroweb/pull/86), upgrade was successful but after 30+ blocks, the chain could not produce a block. This happened on Rococo relay chain and NeuroWeb Testnet.

All collators have block 4238138 as their best block and 4238137 as finalized, but they are constantly trying to create 4238138 block again, and they are stuck in a loop. With following logs:
```
[Parachain] 💤 Idle (14 peers), best: #4238138 (0x186e…165a), finalized #4238137 (0xdf70…ce3d), ⬇ 0.3kiB/s ⬆ 0.8kiB/s
[Parachain] Report 12D3KooWKk4TataMLyBYkEGoZikga2xkQVvEfe6L3UFJvY2iS6ip: -2147483648 to -2147483648. Reason: Same block request multiple times. Banned, disconnecting.
[Relaychain] ✨ Imported #11627941 (0x7e09…08b4)
[Parachain] 🙌 Starting consensus session on top of parent 0xdf704d9ce889278706c9e695c587caa3dcef6633b576b189972c455796ecce3d
[Parachain] 🎁 Prepared block for proposing at 4238138 (351 ms) [hash: 0x1ed58716838be24bea68739874ff8d3fca16319b79f786a14ad53ffde002fc18; parent_hash: 0xdf70…ce3d; extrinsics (26): [0x236c…b58f, 0x46e3…fc58, 0x3a58…9c26, 0xf30d…8df3, 0xb9b3…03d6, 0xe8e6…ed9e, 0x4b0b…caa1, 0xd591…c703, 0xb6e8…0417, 0xa982…3a1f, 0xd151…18b7, 0x2423…1f0e, 0x9e72…2d6e, 0x3129…9dd8, 0xa7c0…9a04, 0xa622…7461, 0xec09…16b5, 0x2f71…e169, 0x4ed7…60f7, 0x678a…039d, 0x7f04…962a, 0x76d5…a05e, 0x8508…4fc0, 0xeb82…2628, 0xc50d…661c, 0x7a1a…af9d]
[Parachain] 🔖 Pre-sealed block for proposal at 4238138. Hash now 0xf9f612927c5910521e11d6effa144c12e2fce2a51ace33d021e6641a723f10d9, previously 
[Parachain] ✨ Imported #4238138 (0xf9f6…10d9)
[Parachain] PoV size { header: 1.0126953125kb, extrinsics: 19.8486328125kb, storage_proof: 534.142578125kb }
[Parachain] Compressed PoV size: 426.7099609375kb
[Relaychain] Trying to remove unknown reserved node 12D3KooWAV1uG1e8gH82RuhYjagTVpfu5aQJ3Vg4sXNFutRhY8o8 from SetId(3).
[Relaychain] Trying to remove unknown reserved node 12D3KooWM3hvXvaShyp7drQCavFHuwobkYdnCp2uHU5iRRAQwsw2 from SetId(3).
[Parachain] Report 12D3KooWQx3qkFdnyvqdg6dpyswAtVfnYTubWELRgcv72HF3978p: -2147483648 to -2147483648. Reason: Same block request multiple times. Banned, disconnecting.
[Parachain] Report 12D3KooWQy5GJRRRLdsiNryAAspbCfeH3resav7JV5gUUTyPfEPc: -2147483648 to -2147483648. Reason: Same block request multiple times. Banned, disconnecting.
[Parachain] Report 12D3KooWRWRmoWd7j5y91FbCkCjxvumicmpXsf5CCL5Zg8Fa1tVs: -2147483648 to -2147483648. Reason: Same block request multiple times. Banned, disconnecting.
[Relaychain] 💤 Idle (10 peers), best: #11627941 (0x7e09…08b4), finalized #11627939 
```

Our assumption is that it is caused by forks on relay chain (Rococo) which are not handled properly by collators on NeuroWeb Testnet. But we would like to get confirmation and better understanding of this issue, so we are sure how to avoid having it on NeuroWeb Mainnet, alongside finding the way to unblock NeuroWeb Testnet.

**Comment by michalkucharczyk** [comment] 2024-08-06 14:27
> Regarding the txpool, @michalkucharczyk any ideas what can be done except regular restarts?

Not really. New pool already looks quite stable, I can offer assistance with testing new pool in your testnet.

**Comment by wilwade** [comment] 2024-10-12 21:02
@bkchr or others, would just switching from the `RevalidationType.Full` to `RevalidationType.Light` resolve the issue in the short term?

https://paritytech.github.io/polkadot-sdk/master/sc_transaction_pool/enum.RevalidationType.html#variant.Light

**Comment by bkchr** [comment] 2024-10-12 21:11
No sadly not. The pr should be merged in the near future and then should be ready to be tested. Best you already try the omni node if that works for you and if yes, you could start using it from master after it got merged.

**Comment by wilwade** [comment] 2024-10-12 21:20
OK. We're seeing this on mainnet so I think we are going to have to make a new pool with a custom strategy to work around it for now.

**Comment by bkchr** [comment] 2024-10-12 21:30
The issue is that the block production reports back "Invalid" transactions. The problem is not the revalidation. You can workaround this by providing a wrapped tx pool to your proposerfactory that doesn't forward `report_invalid` to the wrapped tx pool.

**Closed** 2024-10-15 15:05 UTC
Labels: I5-enhancement

**Comment by michalkucharczyk** [comment] 2024-10-15 15:13
Follow-up work planned here: https://github.com/paritytech/polkadot-sdk/issues/5472

**Comment by magecnion** [comment] 2024-12-10 09:46
Hey @bkchr, we are considering adding the workaround you mentioned [here](https://github.com/frequency-chain/frequency/pull/2196). I want to keep in mind any possible side effects. The only one I can think of is the filling of the pool with invalid transactions. In this case, is there any way to clear it?

Am I missing any other potentially important effects?

**Comment by bkchr** [comment] 2024-12-10 09:52
@magecnion the tx pool transactions are constantly checked for validity. My workaround would lead to block production not being able to tell the pool that a tx is invalid. So, the pool would only find out about invalid transactions by re-checking their validity. (which by the way is the only way non validators find out about invalid tx in their pool)

**Comment by magecnion** [comment] 2024-12-10 15:16
@bkchr I can see that invalid txs (with the `InvalidTransaction::Future` error) are not being removed, and they are included in the next block successfully. However, I noticed this log:
```sh
2024-12-10 16:02:36.083 TRACE tokio-runtime-worker txpool: [Parachain] [0x42ed3e14a19d91ba3485b1f8378e37ab0a5b1f8ae6de68f147f8d1ac9245ffb0] Skipped adding for revalidation: Already there.    
```
As you mentioned, txs are not being validated by block production but are being re-checked by another part of the code (I assume this is the revalidation part). However, this part is skipping the validation, as the log shows. I wonder if this can happen with txs that are invalid for a reason other than the `InvalidTransaction::Future` error, leading to the scenario I mentioned at the beginning: a pool full of invalid transactions.

**Comment by michalkucharczyk** [comment] 2024-12-10 16:48
@magecnion 
I don't know what your environment is - but have you maybe tried a new transaction pool? It shall fix the problem with invalid transactions.

**Comment by magecnion** [comment] 2024-12-11 08:35
@michalkucharczyk my goal in applying the workaround is to make as few modifications as possible until the fork-aware transaction pool is included in a stable release. What exactly do you mean by a _new transaction pool_?

**Comment by bkchr** [comment] 2024-12-11 20:47
> **EDIT**: The previous reasoning was wrong; the skipping refers to the addition of the validation list, not the validation itself. But now I wonder if there is a chance that, in the revalidation process, the invalid transaction — which is now not removed because of the workaround — could be removed by the revalidation part.

The workaround is not touching the revalidation worker. The workaround touches the interface between the block production and the tx pool. With the workaround applied, the block production is not reporting back to the tx pool invalid transaction. However, this does not touch the revalidation which will remove these invalid transactions.
