### ISSUE TITLE
All polkadot parachains are not producing block as usual

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/polkadot-sdk#4225] opened 2024-04-21 11:32 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I checked below networks, they are all having issue to produce block now
1. Astar
2. Acala
3. Ajuna
4. Phala
5. Spiritnet
6. Nodle-Parachain
7. Collectives
8. Centrifuge
9. Polkadex
10. Zeitgeist
11. Nodle
12. Moonbeam
13. Zeitgeist
14. Bifrost

### Steps to reproduce

Can see it on telemetry
https://polkadot.js.org/apps/#/explorer

**Comment by burdges** [comment] 2024-04-21 13:42
This is https://github.com/paritytech/polkadot-sdk/issues/4226

**Comment by alexggh** [comment] 2024-04-21 14:00
Closing this as a duplicate of https://github.com/paritytech/polkadot-sdk/issues/4226.

**Closed by alexggh** 2024-04-21 14:00 UTC
Labels: I2-bug, I10-unconfirmed
