### ISSUE TITLE
Node spams with error logs when self-terminates because of insufficient storage 

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#4264] opened 2024-04-24 08:27 UTC
When node self-terminates because of insufficient with

```
main storage-monitor: Available space 828MiB for path `/chain-data/chains/versi-networking/db/full` dropped below threshold: 1024MiB , terminating... 
```

Then it starts spam the logs with around 900K lines of logs, this puts a strain on our logging framework, so we should try to avoid it if possible.

```
netlink_proto::connection: netlink socket stream shut down
 libp2p_mdns::behaviour: if watch returned an error: rtnetlink socket closed  
 error flushing netlink socket: Custom { kind: Other, error: "A Tokio 1.x context was found, but it is being shutdown.
```

https://grafana.teleport.parity.io/goto/uWFcFOfSR?orgId=1

Note! This is not a flow that normal validators would exercise, so it is just nice to have fix, if it can be done with low effort.

**Comment by sandreim** [comment] 2024-04-24 10:56
What we need is graceful node shutdown for such situations.

**Comment by bkchr** [comment] 2024-05-14 20:41
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/671

**Closed by bkchr** 2024-05-14 20:41 UTC
