### ISSUE TITLE
Refactor parachain client code in such way that it does not require a RuntimeApi

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#3121] opened 2024-01-30 03:07 UTC
There isn't much reason why a parachain client code needs to access RuntimeApi of the runtime. In fact, a fake implementation is used for the system parachains client node. So it serves no purpose other than to make dev's life more miserable.

**Comment by bkchr** [comment] 2024-01-30 09:22
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/27

**Closed by bkchr** 2024-01-30 09:22 UTC
