### ISSUE TITLE
Transactions is never included on the next block

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1327] opened 2023-08-31 05:06 UTC
Our team have observed that on most, if not all, parachains, transaction confirmation time is never less than 12s. i.e. They are never included on the next block.

I did 30 transfers on the asset hub rococo and this is the result

```
2023-08-31T04:57:28.745Z :  Avg 20.31816666666667 s
2023-08-31T04:57:28.745Z :  Min 13.763 s
2023-08-31T04:57:28.745Z :  Max 30.589 s
```

Is there something can be done to improve this? I know async backing can help, but still want to know what if there is a bottleneck that can be fixed

Related issues:
https://github.com/AcalaNetwork/Acala/issues/2527
https://github.com/moonbeam-foundation/moonbeam/issues/2286

**Comment by seunlanlege** [comment] 2023-08-31 07:21
Do you think this have anything to do with extrinsic mortality?

**Comment by xlc** [comment] 2023-08-31 08:08
I don’t think so. This can also be observed on Moonbeam with EVM transactions, which I don’t think have mortality.

**Comment by bkchr** [comment] 2023-08-31 08:12
I think the issue is this: https://github.com/paritytech/polkadot-sdk/issues/1202

One of the problems is that it actually reports inclusion way too late. Not sure about the direct inclusion, but this could also be influenced by this.

**Comment by bkchr** [comment] 2024-04-22 19:43
Should be fixed by: https://github.com/paritytech/polkadot-sdk/commit/b25d29a50247f284cde5b24e270b6db7b4a81e7e

**Closed by bkchr** 2024-04-22 19:43 UTC
