### ISSUE TITLE
Fix flaky zombienet test `zombienet-cumulus-0002-pov_recovery`

### ISSUE THREAD

**Issue by pepoviola** [paritytech/polkadot-sdk#6573] opened 2024-11-21 10:04 UTC
Some examples from Tuesday 

**Fail to start (node *three*)**
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786180
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7785532
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7784688
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7784356
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7784158
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7778904
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7778369

https://grafana.teleport.parity.io/goto/YZ5Wuv7Ng?orgId=1
```

2024-11-19 23:27:57.675 | 0: rust_begin_unwind |  
-- | -- | --
  |   | 2024-11-19 23:27:57.676 | 1: core::panicking::panic_fmt |  
  |   | 2024-11-19 23:27:57.676 | 2: core::panicking::panic |  
  |   | 2024-11-19 23:27:57.676 | 3: futures_util::future::future::FutureExt::poll_unpin |  
  |   | 2024-11-19 23:27:57.677 | 4: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll |  
  |   | 2024-11-19 23:27:57.682 | 5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll |  
  |   | 2024-11-19 23:27:57.683 | 6: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll |  
  |   | 2024-11-19 23:27:57.683 | 7: polkadot_overseer::spawn::{{closure}} |  
  |   | 2024-11-19 23:27:57.684 | 8: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll |  
  |   | 2024-11-19 23:27:57.684 | 9: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll |  
  |   | 2024-11-19 23:27:57.685 | 10: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll |  
  |   | 2024-11-19 23:27:57.691 | 11: tokio::runtime::context::runtime::enter_runtime |  
  |   | 2024-11-19 23:27:57.694 | 12: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll |  
  |   | 2024-11-19 23:27:57.695 | 13: tokio::runtime::task::core::Core<T,S>::poll |  
  |   | 2024-11-19 23:27:57.695 | 14: tokio::runtime::task::harness::Harness<T,S>::poll |  
  |   | 2024-11-19 23:27:57.696 | 15: tokio::runtime::blocking::pool::Inner::run |  
  |   | 2024-11-19 23:27:57.696 | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. |  
  |   | 2024-11-19 23:27:57.697 | 2024-11-19 22:27:57.697  WARN tokio-runtime-worker polkadot_overseer: [Relaychain] Terminating due to subsystem exit subsystem="network-bridge-rx" |  
  |   | 2024-11-19 23:27:57.697 | 2024-11-19 22:27:57.697  WARN tokio-runtime-worker polkadot_overseer: [Relaychain] termination error detected, dropping but terminating the execution subsystem="network-bridge-rx" err=Canceled |  
  |   | 2024-11-19 23:27:57.697 | 2024-11-19 22:27:57.697 ERROR tokio-runtime-worker overseer: [Relaychain] subsystem finished unexpectedly subsystem=Ok(())


```

**Job timeout (1hr)**
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786118
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7785725
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7785632
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7785631
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7785467
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7785047
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7785046
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7784814
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7784395
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7784394
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7784326
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7783865
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7783800
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7783336
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782963
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782782
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782653
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782364
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782290
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782160
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782095
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7782030
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7781962
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7781897
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7780855
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7780523
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7780495
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7780314
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7780056
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779863
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779772
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779765
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779680
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779553
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779490
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779425
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779332
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779298
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779102
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779102
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7779036
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7778876
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7778239

cc: @paritytech/sdk-node

**Comment by pepoviola** [comment] 2024-12-05 15:20
Failures from yesterday

zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery
zombienet-cumulus-0002-pov_recovery


cc: @paritytech/sdk-node

**Comment by skunert** [comment] 2024-12-16 11:04
This zombienet test also fails locally consistently at registering the parachain. The tx sent here is not finalized. 
https://github.com/paritytech/polkadot-sdk/blob/482bf08290c2ff2812eb1235f551740f0e6576df/cumulus/zombienet/tests/0002-pov_recovery.zndsl#L9-L9 

This is really strange. I found the issue was introduced with #6400. Not sure why removing the network starter causes grandpa issue. Reverting that PR makes the test pass again.

@paritytech/networking Please take a deeper look into this.

**Comment by bkchr** [comment] 2024-12-16 11:11
@skunert can you please more logs? What you mean by the "tx is not finalized"? Only the tx never makes it into a block or does finality doesn't work at all?

**Comment by pepoviola** [comment] 2024-12-16 11:15
Finalization doesn't work at all when we use the _reserved_ flags
https://github.com/paritytech/polkadot-sdk/pull/6773#issuecomment-2543869263

Thx!

**Comment by skunert** [comment] 2024-12-16 11:21
@bkchr assembled some more logs:


- logs from `validator-0` with `grandpa=trace` with #6400 in place:
[validator-0_broken.log](https://github.com/user-attachments/files/18149073/validator-0_broken.log)
No blocks getting finalized.

- logs from `validator-0` with `grandpa=trace` with #6400 reverted:
[validator-0_working_6400_reverted.log](https://github.com/user-attachments/files/18149080/validator-0_working_6400_reverted.log)

All node logs:
[working.zip](https://github.com/user-attachments/files/18149087/working.zip)

[broken.zip](https://github.com/user-attachments/files/18149102/broken.zip)

**Comment by dmitry-markin** [comment] 2024-12-16 11:47
Let me clarify, the finalization is stalled if and only if both is true:

1. https://github.com/paritytech/polkadot-sdk/pull/6400 is in place
2. `--reserved-only` is passed?

**Comment by skunert** [comment] 2024-12-16 12:33
> Let me clarify, the finalization is stalled if and only if both is true:
> 
> 
> 
> 1. https://github.com/paritytech/polkadot-sdk/pull/6400 is in place
> 
> 2. `--reserved-only` is passed?

That is the working assumption. In my tests I focused on finding the commit that broke it. Did not verify the involvement of the reserved only flag.

**Comment by pepoviola** [comment] 2024-12-16 13:09
I just deploy to networks ( from latest image of master), with `--reserved-only` the finalization doesn't work at all, here are the logs https://grafana.teleport.parity.io/goto/S1zBJdIHR?orgId=1

And without the flag finalization works as expected, here are the logs https://grafana.teleport.parity.io/goto/ss2DJdIHg?orgId=1

I will deploy other networks (without #6400) to check if the behavior is the same.

Thx!

**Comment by pepoviola** [comment] 2024-12-16 18:54
Small update, I deployed the same config with the previous commit from master ([05ad5475dec748a8a30685bc29a7caba6e63c7ab](https://github.com/paritytech/polkadot-sdk/commit/05ad5475dec748a8a30685bc29a7caba6e63c7ab)) and both cases works as expected. Here are the losg:
With __reserved__ https://grafana.teleport.parity.io/goto/rF45nFINg?orgId=1
Without https://grafana.teleport.parity.io/goto/bvu5nKINR?orgId=1

Thx!

**Comment by dmitry-markin** [comment] 2024-12-24 13:58
Why are we passing `--reserved-only` in the first place? Even with the network starter present finalization is lagging behind. On average only every second-third block is finalized: #0, #3, #5, #8, #10, etc. This is likely because the validators are only syncing blocks through the bootnode, because they are only connected to it on the sync protocol.

Without `--reserved-only` all the 13 nodes (bootnode + 12 validators) are connected to each other on the sync protocol, and in this case every block is finalized: #0, #1, #2, #3, #4, #5, #6, #7, #8, #9, #10, etc

**Comment by dmitry-markin** [comment] 2024-12-26 20:49
What happens here is that due to removed network starter networking starts first and connects to reserved peers on default (sync) protocol before `grandpa-voter` task finishes initialization, and the latter misses `SyncEvent::PeerConnected(peer_id)` event.

Because we abuse the reserved nodes mechanism on non-default protocols to track sync peers, `GossipEngine` in grandpa listens to `SyncEvent::PeerConnected(peer_id)` events to add such peers as reserved on `/grandpa/1` notifications protocol. And because `grandpa-voter` task is not ready yet to receive sync events, it misses this event and does not add the peer as reserved effectively never connecting to it on `/grandpa/1` notifications protocol.

When `--reserved-only` is not specified, networking also discovers peers later via Kademlia, and for those peers grandpa's `GossipEngine` is ready to receive sync events.

This issue can potentially manifest in the wild if a node is configured to connect only to `--reserved-nodes`, and connections are established fast enough for additional tasks to not finish the initialization.

**Comment by dmitry-markin** [comment] 2024-12-27 16:57
The issue is fixed by https://github.com/paritytech/polkadot-sdk/pull/7011.

**Closed** 2024-12-30 15:02 UTC
Labels: T10-tests
